vich_uploader:
    db_driver: orm

    mappings:
        vinyl:
            uri_prefix: /uploads/vinyls
            upload_destination: '%kernel.project_dir%/public/uploads/vinyls'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer